/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BitacoraAseguradora;
import controller.BitacoraIncidente;
import controller.BitacoraVehículos;
import controller.ColaCotizacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.event.TableModelListener;
import javax.swing.JTable;
/**
 *
 * @author myria
 */
public class ReporteIncidente extends javax.swing.JFrame {
    BitacoraAseguradora ba;
    BitacoraVehículos bv;    
    ColaCotizacion cola;
    BitacoraIncidente bi;
    int contadorTemp = 0;
    String TempDataReporte[][] = new String[99][3];
    /**
     * Creates new form ReporteIncidente
     * @param ba
     * @param bv
     * @param bi
     * 
     */
    
    
    public ReporteIncidente(BitacoraAseguradora ba, BitacoraVehículos bv, BitacoraIncidente bi, ColaCotizacion cola) {
        this.ba = ba;
        this.bv = bv;
        this.bi= bi;
        this.cola = cola;
        initComponents();
        
        this.cBoxTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(bv.getMecanica()));
        this.cBoxRepuesto.setModel(new javax.swing.DefaultComboBoxModel<>(bv.getRepuesto()));
        
        this.jButton2.setEnabled(false);
    }

    private ReporteIncidente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cBoxTipoServicio = new javax.swing.JComboBox<>();
        cBoxRepuesto = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaIndicentes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTE INCIDENTE AUTOMAS");

        jLabel1.setText("DPI ASEGURADO");

        jLabel2.setText("DPI TERCERO");

        jLabel3.setText("TIPO SERVICIOS");

        jLabel4.setText("REPUESTOS");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        cBoxTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cBoxTipoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoServicioActionPerformed(evt);
            }
        });

        cBoxRepuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("El asegurado es culpable");

        jCheckBox2.setText("El tercero tiene seguro");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablaIndicentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaIndicentes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(cBoxTipoServicio, 0, 189, Short.MAX_VALUE)
                            .addComponent(cBoxRepuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 136, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cBoxTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cBoxRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jButton2.setText("REPORTAR INCIDENTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jButton2)
                .addGap(84, 84, 84)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(74, 74, 74)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cBoxTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxTipoServicioActionPerformed
    
  
    
        
    
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void anadirDetalleTemp(String Correlativo, String repuesto, String Precio){        
        
        if(contadorTemp<99){                
            this.TempDataReporte[contadorTemp][0] = Correlativo;
            this.TempDataReporte[contadorTemp][1] = repuesto;
            this.TempDataReporte[contadorTemp][2] = Precio;
            contadorTemp++;
        }        
    }
    
    private String[][] getArrayToTable(){
        String dataReturn[][] = new String[contadorTemp][3]; 
        for (int i = 0; i < contadorTemp; i++) {
            dataReturn[i][0] = this.TempDataReporte[i][0];
            dataReturn[i][1] = this.TempDataReporte[i][1];
            dataReturn[i][2] = this.TempDataReporte[i][2];
        }
        return dataReturn;
    }
    
    public String generaCorrelativo(){
        double numAleatorio;
        String cadenaCorrelativo="";

        for (int i=0; i < 5; i++) {

         numAleatorio=  Math.floor(Math.random()*9+1) ;
         cadenaCorrelativo = (cadenaCorrelativo + String.valueOf(numAleatorio));

         }
         String numero=cadenaCorrelativo.replace(".", "");
         String correlativo=numero.replace("0", "");

            return correlativo;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
            String repuesto=cBoxRepuesto.getSelectedItem().toString();
            String servicio=cBoxTipoServicio.getSelectedItem().toString();
            
            this.jTextField1.setEnabled(false);
            this.jTextField2.setEnabled(false);
                                    
            String Correlativo1 = this.generaCorrelativo();
            String Correlativo2 = this.generaCorrelativo();
            String Precio = bv.getPrecioRepuesto(repuesto)+"";
            String Precio2 = bv.getPrecioMecanica(servicio)+"";
            
            this.anadirDetalleTemp(Correlativo1, repuesto, Precio);            
            this.anadirDetalleTemp(Correlativo2, servicio, Precio2);
            
            float resultado = 0;
                                                         
            for (int i = 0; i < contadorTemp; i++) {               
               
               resultado += Float.parseFloat(this.TempDataReporte[i][2]);
               
            }
            
            String nombreColumnasReincidente[] = {"CODIGO", "NOMBRE", "PRECIO"};                   
            String dataIncidente[][] = this.getArrayToTable();
            jTablaIndicentes.setModel(new DefaultTableModel(dataIncidente, nombreColumnasReincidente));
            
            
            this.jTextField3.setText(resultado + "");
             
            this.jButton2.setEnabled(true);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Codigo = 1;
        float DPIAsegurado= Float.parseFloat(jTextField1.getText());
        float DPITercero= Float.parseFloat(jTextField2.getText());
        boolean aseguradoCulpable= jCheckBox1.isSelected();
        boolean terceroSeguro= jCheckBox2.isSelected();
        float CostoReal= Float.parseFloat(jTextField3.getText());
        float PagoRequerido = 0;    
        String RolAsegurado="";
        String RolTercero="";
        String Estado = "Proceso";
        String Pago = "Pendiente";
//        String terceroAsegurado
//        
//        
//        if (terceroSeguro){
//            
//        }
        
        if(aseguradoCulpable){
            RolAsegurado = "Autor";
            RolTercero = "Afectado";
        }else{
            RolAsegurado = "Afectado";
            RolTercero = "Autor";
        }
                                                                       
        if (cola.dpiExiste(DPIAsegurado)) {
            this.jTextField1.setEnabled(false);
            if (cola.dpiExiste(DPITercero)) {
                /* Metodo agregar Bitacora de incidentes*/
                
                System.out.println(" 1. "+RolAsegurado +" 2. "+ RolTercero+" 3. "+DPIAsegurado+" 4. "+DPITercero+" 5. "+CostoReal+" 6. "+PagoRequerido+" 7. "+Estado+" 8. "+Pago);
                
                bi.anadirIncidente(Codigo, RolAsegurado, RolTercero, DPIAsegurado, DPITercero, CostoReal, PagoRequerido, Estado, Pago, terceroSeguro);
                                
                
                JOptionPane.showMessageDialog(null, "Incidente, ingresado correctamente");
                
                
                
                this.setVisible(false);
                Administrator Admin = new Administrator(ba,bv,bi,cola);
                Admin.setVisible(true);
                
                
            }else{
                if(terceroSeguro){               
                    JOptionPane.showMessageDialog(null, "Valide que ingrese el DPI correcto, debido a que no existe en el historial de asegurados");
                    this.jTextField2.setEnabled(true);
                }else{
                    this.jTextField2.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "El DPI de tercero no existe y no esta asegurado, por favor ingrese los siguientes datos");

                    String Nombres = JOptionPane.showInputDialog("Ingresa tu Nombre");
                    String Apellidos = JOptionPane.showInputDialog("Ingresa tu Apellido");
                    String Telefono = JOptionPane.showInputDialog("Ingresa tu Telefono");

                    System.out.println(Nombres+" "+Apellidos+" "+Telefono);

                    this.jTextField2.setEnabled(false);

                    JOptionPane.showMessageDialog(null, "Usuario agregado correctamente");

                    JOptionPane.showMessageDialog(null, "Presione nuevamente el boton de reportar Incidente");

                    cola.anadirCotizacion(Nombres, Apellidos, "", "", "", "", Integer.parseInt(Telefono), 0, 3, 1, DPITercero, 0, 0, 0, 0, 0);

                    
                }
                
            }
        }else {
            this.jTextField1.setEnabled(true);
            JOptionPane.showMessageDialog(null, "No existe DPI del asegurado, valide el DPI que se ingreso");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        Administrator Admin = new Administrator(ba,bv,bi,cola);
        Admin.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReporteIncidente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBoxRepuesto;
    private javax.swing.JComboBox<String> cBoxTipoServicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTablaIndicentes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
